import Head from 'next/head'
import { gql, useQuery } from '@apollo/client'
import styled from 'styled-components';
import MyInfoWrap from '@/components/blocks/MyInfoWrap';
import WeatherBlock from '@/components/blocks/WeatherBlock';




const WrapperOne = styled.div`
    margin-right: 40px;
`;

const WrapperTwo = styled.div`
   display: flex;
   width: 674px;
   justify-content: space-between;
`;

const AllLinksQuery = gql`
  query{
    links{
      id
      title
      url
      description
      imageUrl
      category
    }
  }
`;
export default function Home() {
  const { data, loading, error } = useQuery(AllLinksQuery);
  if(loading) return <p>Loading...</p>
  if(error) return <p>oh no... {error.message}</p>
  return (
    <>
      <Head>
        <title>Jian</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
        <WrapperOne>
          <MyInfoWrap />
        </WrapperOne>

        <WrapperTwo>
          <WeatherBlock />
          {/* <WeatherBlock /> */}
        </WrapperTwo>
      
    </>
  )
}
